import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    //TELA INICIAL
    container: {
        height: height * 1,
        marginTop: 30,
        padding: 20,
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    imagemFundo: {
        paddingHorizontal: 20,
        flex: 1,
        justifyContent: 'center',
    },
    content: {
        width: width * 0.9,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageContainer: {
        width: 140,
        height: 100,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logo: {
        resizeMode: 'contain',
        width: '100%',
        height: '100%', 
    },
    titulo: {
        fontSize: 28,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 5,
        padding: 10,
        letterSpacing: 2,
    },
    texto: {
        fontSize: 18,
        color: 'black',
        fontWeight: '500',
        marginVertical: 5,
        padding: 5,
    },
    input: {
        fontSize: 18,
        backgroundColor: '#fefaf1',
        marginVertical: 5,
        height: 50,
        width: width * 0.8,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
    },
    iconContainer: {
        position: 'absolute',
        right: 10,
        top: 18,
        zIndex: 1,
    },
    buttonPrincipal: {
        marginTop: 20,
        marginBottom: 10,
        width: '60%',
        backgroundColor: '#606060',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
    },
    buttonTextPrincipal: {
        fontSize: 18,
        color: 'white',
        fontWeight: '500',
        textAlign: 'center',
    },
    buttonSecundario: {
        marginTop: 10,
        width: '60%',
        paddingVertical: 10,
        paddingHorizontal: 20,
    },
    buttonTextSecundario: {
        fontSize: 16,
        textAlign: 'center',
    },
    errorContainer: {
        alignItems: 'center',
        marginTop: 10,
        padding: 5,
    },
    errorMessage: {
        marginTop: 5,
        textAlign: 'center',
        fontSize: 16,
        color: 'red',
        fontWeight: '500',
    },

    //TELA DE CADASTRO
    containerCadastro: {
        height: height * 1,
        marginTop: 30,
        padding: 10,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentCabecalhoCadastro: {
        flexDirection: 'row',
        width: width * 0.9,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentFormularioCadastro: {
        padding: 10,
        width: width * 0.9,
        justifyContent: 'flex-start',
    },
    contentBotoesCadastro: {
        width: width * 0.9,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    tituloCadastro: {
        fontSize: 26,
        fontWeight: '500',
        textAlign: 'center',
        marginTop: 18,
        paddingHorizontal: 10,
        letterSpacing: 2,
    },
    textoCadastro: {
        fontSize: 18,
        fontWeight: '500',
        marginVertical: 5,
    },
    inputCadastro: {
        backgroundColor: '#fefaf1',
        fontSize: 18,
        marginVertical: 5,
        height: 40,
        width: '100%',
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
    },
    imageContainerCadastro: {
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
    },

    //HOME
    containerHome: {
        flexDirection: 'column',
        marginTop: 30,
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#252525',
    },
    contentCabecalhoHome: {
        width: width * 0.9,
        padding: 10,
        marginTop: 10,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    textoCabecalhoHome: {
        color: 'white',
        padding: 2,
        fontSize: 22,
        textAlign: 'center',
        letterSpacing: 1,
    },
    contentBotoesHome: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        width: width * 0.9,
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingVertical: 5,
    },
    boxHome: {
        alignItems: 'flex-start',
        marginTop: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        width: '100%',
        height: 120,
        borderRadius: 5,
        padding: 10,
    },
    subBoxHome: {
        flexDirection: 'row',
        padding: 10,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    textoBoxHome: {
        fontWeight: '500',
        letterSpacing: 2,
        padding: 3,
        fontSize: 15,
        borderRadius: 5,
        width: '100%',
        textAlign: 'center',
        backgroundColor: '#f5ffc4',
    },
    subTextoBoxHome: {
        paddingHorizontal: 5,
        fontSize: 14,
        width: '100%',
        textAlign: 'left',
        color: 'white',
    },
    subTextoBoxHomeLabel: {
        paddingHorizontal: 5,
        fontSize: 14,
        width: '100%',
        textAlign: 'left',
        color: 'white',
    },
    botoesHome: {
        width: '43%',
        height: 100,
        backgroundColor: '#fefaf1',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginVertical: 10,
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 3,
    },
    imageContainerHome: {
        width: 50,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    imageBotoesHome: {
        resizeMode: 'contain',
        width: '100%',
        height: '100%', 
    },
    textoBotoesHome: {
        fontWeight: '500',
        padding: 2,
        fontSize: 16,
        textAlign: 'center',
    },
    contentSearchBar: {
        padding: 10,
        width: width * 0.9,
        marginTop: 10,
        marginBottom: 10,
    },
    searchBarHome: {
        backgroundColor: '#fefaf1',
        fontSize: 14,
        height: 40,
        borderWidth: 1,
        borderColor: 'white',
        paddingLeft: 35,
        paddingRight: 10,
        borderRadius: 5,    
    },
    iconContainerHome: {
        position: 'absolute',
        left: 15,
        top: 17,
        zIndex: 1,
    },
    //AGENDA
    containerServicos: {
        alignItems: 'center',
        marginTop: 5,
        padding: 10,
    },
    agendaTexto: {
        fontSize: 18,
        fontWeight: '500',
    },
    agendaTextoB: {
        fontSize: 14,
        textAlign: 'center',
        marginTop: 5,
    },

    //TELAS DE CLIENTES, SERVIÇOS, PAGAMENTOS, ETC
    containerTelaPadrao: {
        flex: 1,
        flexDirection: 'column',
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#252525',
    },
    contentFormulario: {
        width: width * 0.9,
        alignSelf: 'stretch',
        padding: 15,
        backgroundColor: '#fefaf1',
        borderRadius: 10,
        marginBottom: 5,
    },
    contentListaClientes: {
        marginVertical: 10,
        width: width * 0.9,
        borderRadius: 5,
        padding: 10,
        flex: 3,
        backgroundColor: '#fefaf1',
    },
    contentListaPagamentos: {
        marginVertical: 10,
        width: width * 0.9,
        borderRadius: 10,
        padding: 10,
        flex: 3,
        backgroundColor: '#fefaf1',
    },
    tituloPadrao: {
        fontWeight: '600',
        padding: 5,
        fontSize: 16,
        textAlign: 'center',
    },
    subTituloPadrao: {
        marginVertical: 5,
        padding: 3,
        fontSize: 16,
        textAlign: 'center',
    },
    inputPadrao: {
        marginTop: 8,
        paddingHorizontal: 15,
        fontSize: 16,
        height: 35,
        borderWidth: 1,
        borderRadius: 5,
        borderColor: 'gray',
    },
    botaoPadrao: {
        marginTop: 10,
        marginBottom: 5,
        padding: 10,
        width: width * 0.9,
        backgroundColor: '#f5ffc4',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    botaoPadraoB: {
        marginTop: 15,
        paddingVertical: 10,
        paddingHorizontal: 15,
        backgroundColor: '#252525',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentPicker: {
        justifyContent: 'center',
        textAlign: 'center',
        height: 40,
        paddingVertical: 20,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
    },
    contentPickerB: {
        marginTop: 8,
        justifyContent: 'center',
        height: 37,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
    },
    inputB: {
        marginTop: 10,
        fontSize: 16,
        backgroundColor: '#fefaf1',
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 15,
    },
    pickerClientes: {
        fontSize: 16,
    },
    pickerEstados: {
        fontSize: 16,
    },
    dataInput: {
        alignContent: 'center',
        justifyContent: 'center',
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
    },
    dataInputB: {
        paddingHorizontal: 15,
        marginTop: 10,
        alignItems: 'flex-start',
        alignContent: 'center',
        justifyContent: 'center',
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
    },

    //PERFIL
    inputDadosPerfil: {
        width: width * 0.85,
        borderRadius: 5,
        marginVertical: 5,
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderWidth: 1,
        fontSize: 16,
        fontWeight: '500',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    editIcon: {
        position: 'absolute',
        right: 10,
    },
    successMessage: {
        color: 'blue',
        fontWeight: '500',
        marginTop: 10,
        fontSize: 16,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        alignContent: 'center',
    },

    //PAGAMENTOS
    contentPickerC: {
        marginTop: 10,
        justifyContent: 'center',
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
    },
    subTituloPadraoB: {
        fontSize: 16,
        textAlign: 'center',
    },
    subTituloPadraoC: {
        paddingVertical: 5,
        fontSize: 15,
        textAlign: 'center',
    },
    subTituloPadraoD: {
        paddingVertical: 5,
        fontSize: 15,
        textAlign: 'center',
        fontWeight: '500',
    },
});